pool:
  vmImage: "ubuntu-latest"

trigger:
  - trunk

# define variables to use during the build
variables:
  - group: PROD Kubernetes Deploy Variables
  - name: buildOutputFolder
    value: "app/build/**"
  - name: appFolder
    value: "app"
  - name: componentTestFolder
    value: "component-test"
  - name: imageNameOfComponentTest
    value: "runner"
  - name: "projectName"
    value: "admin-portal"
  - name: "registryServerName"
    value: "$(azure-registry-name).azurecr.io"
  - name: "DEPLOY_VERSION"
    value: "$(Build.BuildId)"

steps:
  - template: ci/templates/build-template.yml
    parameters:
      steps:
        - script: |
            (cd $(appFolder) && yarn install && cd ..)
          displayName: "yarn install"
        - script: |
            (cd $(appFolder) && yarn run build && cd ..)
          displayName: "yarn build"

  - template: ci/templates/unit-tests-template.yml
    parameters:
      appFolder: $(appFolder)

  - template: ci/templates/component-tests-template.yml
    parameters:
      imageNameOfComponentTest: $(imageNameOfComponentTest)
      componentTestFolder: $(componentTestFolder)
      pathTestResultFiles: "**/component-test/results/junit.xml"

  - template: ci/templates/pre-deploy-template.yml

  - template: ci/templates/docker-config-template.yml
    parameters:
      kubernetesCluster: "b2b-gb-aks-int"
      namespace: dev
      command: package
      chartPath: "ci/charts/admin-portal"
      deployVersion: $(DEPLOY_VERSION)
      projectName: $(projectName)
      registryServerName: $(registryServerName)
