sonar.projectKey=admin-portal
sonar.projectName=admin-portal
sonar.sourceEncoding=UTF-8
sonar.exclusions=app/**/node_modules/**, app/src/**/*.test.jsx,app/src/**/*.test.js, app/src/index.tsx, app/src/config/setupTests.js
sonar.sources=app/src
sonar.tests=app/src/
sonar.test.inclusions=app/src/**/*.test.js,app/src/**/*.test.jsx
sonar.typescript.lcov.reportPaths=app/coverage/lcov.info
sonar.testExecutionReportPaths=app/coverage/jest-sonar-reporter.xml
sonar.ts.tslintconfigpath=tslint.json